spring.application.name=com.K23CNT1Ptp.lesson7
# C?u hình k?t n?i Database (ví d? cho MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/ten_database_cua_ban
spring.datasource.username=root
spring.datasource.password=123456789

# C?u hình JPA
spring.jpa.hibernate.ddl-auto=update # T? ??ng update b?ng khi entity thay ??i
spring.jpa.show-sql=true # Hi?n th? câu l?nh SQL trong console