spring.application.name=K23CNT1_Ptp_2310900081_Project3


spring.datasource.url=jdbc:mysql://localhost:3306/ptp_web_ban_giay?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=@Phong7122005


spring.jpa.hibernate.ddl-auto=update


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


ptp.upload.path=./src/main/resources/static/images/product-images/


server.port=8085